### ISSUE TITLE
how to fix hydration error?

### ISSUE THREAD

**Issue by reslear** [GaborTorma/nuxt-dayjs-i18n#2]
<img width="468" alt="Screenshot 2023-10-18 at 12 51 40" src="https://github.com/GaborTorma/nuxt-dayjs-i18n/assets/12596485/5a6b32dd-b8ca-4af0-9085-423052fb1ea5">

used syntax: 
```vue
{{ $df(item.updatedAt, 'LL') }}
// or
{{ $dayjs(item.updatedAt).format('LL') }}
```

**Comment by reslear** [comment]
oh fixed simple add v-if:

```vue
<div v-if="item.updatedAt">
  {{ $df(item.updatedAt, 'LL') }}
</div>
```

**Comment by GaborTorma** [comment]
I think `item.updatedAt` is undefined on server side

**Comment by reslear** [comment]
Uh, that didn't help, so it turns out 

it does hydration on the server with the selected language - as if it caches only the first one, when you refresh the page with another language - there is already a hydration problem. 

also same is add:

```ts
definePageMeta({
  key: (route) => route.fullPath,
})
```

**Comment by GaborTorma** [comment]
Can you provide a minimal repo?

**Comment by reslear** [comment]
https://stackblitz.com/edit/nuxt-dayjs-i18n-xtqkqq

1. Change locale to `hu`
2. after `prefix_except_default` update url and reload page
3. re-inspect frame


https://github.com/GaborTorma/nuxt-dayjs-i18n/assets/12596485/1cc4dcbb-93c0-443c-a540-8ed3a5ef46cb

**Comment by reslear** [comment]
temporally worked solution 

```vue
<time :datetime="item.updatedAt">
  <ClientOnly :fallback="item.updatedAt">{{ $df(item.updatedAt, 'LL') }}</ClientOnly>
</time>
```

**Comment by GaborTorma** [comment]
Unfortunately the Day.js is not SSR ready. Server-side generated with the default locale.

**Comment by GaborTorma** [comment]
I found a solution. I will release a new version in few days.

**Comment by GaborTorma** [comment]
Fixed in [v.2.0.0](https://github.com/GaborTorma/nuxt-dayjs-i18n/releases/tag/v2.0.0)
Make sure don't define defaultLocale in dayjs config. I comes from i18n.locale.

**Comment by GaborTorma** [comment]
Use dayjs-nuxt@2.1.9

**Comment by reslear** [comment]
Updated, works like a charm :) you are awesome !
