### ISSUE TITLE
need fix warn in build step 

### ISSUE THREAD

**Issue by reslear** [GaborTorma/nuxt-dayjs-i18n#4]
So i don't use `dayjs.locale` in all project

But i see in build step:
 ```
  WARN  Use i18n.setLocale instead of dayjs.locale                                                                                           
  ```

<img width="564" alt="Screenshot 2023-10-18 at 15 02 58" src="https://github.com/GaborTorma/nuxt-dayjs-i18n/assets/12596485/d428a279-1296-4882-9fbd-b32574df768e">

```

devDependencies:
@gabortorma/nuxt-dayjs-i18n 1.9.2
└─┬ dayjs-nuxt 2.1.7 peer
  └── dayjs 1.11.10
dayjs-nuxt 2.1.7
└── dayjs 1.11.10
```

**Comment by GaborTorma** [comment]
Fixed in [v.2.0.0](https://github.com/GaborTorma/nuxt-dayjs-i18n/releases/tag/v2.0.0)

**Comment by reslear** [comment]
works 👍
