### ISSUE TITLE
provideFormat - breaks NuxtAppInjections

### ISSUE THREAD

**Issue by reslear** [GaborTorma/nuxt-dayjs-i18n#5]
- <img width="639" alt="Screenshot 2023-10-19 at 12 38 08" src="https://github.com/GaborTorma/nuxt-dayjs-i18n/assets/12596485/09169008-0788-4192-bbe3-ba000069f17a">

in `/.nuxt/types/plugins.d.ts` line with `@gabortorma/nuxt-dayjs-i18n/dist/runtime/plugins/provideFormat').default` has no import by default.

```ts

// .nuxt/types/plugins.d.ts
InjectionType<
  typeof import('../../../../node_modules/.pnpm/@gabortorma+nuxt-dayjs-i18n@1.9.2_@nuxtjs+i18n@8.0.0-rc.5_dayjs-nuxt@2.1.8/node_modules/@gabortorma/nuxt-dayjs-i18n/dist/runtime/plugins/provideFormat').default
>
```

<img width="365" alt="Screenshot 2023-10-19 at 12 43 23" src="https://github.com/GaborTorma/nuxt-dayjs-i18n/assets/12596485/3c149509-a250-4eda-81e5-aa848bdf0da8">

hotfix: 
patch package and add to end lines: 

```diff
diff --git a/dist/runtime/plugins/provideFormat.d.ts b/dist/runtime/plugins/provideFormat.d.ts
index 057ace7b10e85af0de685b3170fe0e8b3fcbc8f8..cda1b725078b94edafa98dd1844f653d063e7a0c 100644
--- a/dist/runtime/plugins/provideFormat.d.ts
+++ b/dist/runtime/plugins/provideFormat.d.ts
@@ -39,3 +39,6 @@ declare module 'vue' {
 		$df(date: string | number | Date | Dayjs, template: string): string
 	}
 }
+
+declare const _default: any;
+export default _default;
```

**Comment by GaborTorma** [comment]
Today, later I will fix it.

**Comment by GaborTorma** [comment]
Fixed in [v.2.0.0](https://github.com/GaborTorma/nuxt-dayjs-i18n/releases/tag/v2.0.0)

**Comment by reslear** [comment]
tested - works 👍
